/*
 * GBDK-2020 Exported Tiles Header
 * Generated by GB-TileStudio 2020
 */

#ifndef NEW_TILESET_H
#define NEW_TILESET_H

#define new_tileset_TILE_COUNT 1

extern const unsigned char new_tileset[];

#endif
